- name: Enable Rancher inbound cluster traffic
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    src: 10.42.0.0/15
    dest: 10.42.0.0/15
    direction: in
    interface: any
  loop:
    - 80
    - 443
  register: result
  retries: 3
  delay: 1
  until: result is not failed

- name: Enable Rancher to cluster node web traffic.
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    src: 10.42.0.0/15
    dest: '{{ vm_ipsddress }}'
    direction: in
    interface: any
  loop:
    - 80
    - 443
  register: result
  retries: 3
  delay: 1
  until: result is not failed

- name: Allow Rancher forwarded traffic
  community.general.ufw:
    rule: allow
    route: yes
    src: 10.42.0.0/15
    dest: 10.42.0.0/15
  register: result
  retries: 3
  delay: 1
  until: result is not failed

- name: Reload UFW
  community.general.ufw:
    state: reloaded
  register: result
  retries: 3
  delay: 1
  until: result is not failed

- name: Add Rancher Helm repo
  kubernetes.core.helm_repository:
    repo_name: rancher-latest
    repo_url: https://releases.rancher.com/server-charts/latest

- name: Export KUBECONFIG variable
  shell: export KUBECONFIG=/root/.kube/config
  when: vm_initialnode

- name: Ensure cert dir exists
  file:
    path: /etc/rancher/ssl
    state: directory

- name: Copy Rancher cert chain
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
    owner: rancher
  loop:
    - { src: files/rancher-ingress.crt, dest: /etc/rancher/ssl/rancher-ingress.crt, mode: '0744' }
    - { src: files/rancher-ingress.key, dest: /etc/rancher/ssl/rancher-ingress.key, mode: '0700' }
    - { src: files/cacerts.crt, dest: /etc/rancher/ssl/cacerts.pem, mode: '0744' }

- name: Create Rancher kubernetes namespace
  kubernetes.core.k8s:
    name: cattle-system
    kind: namespace
    api_version: v1
    state: present
  when: vm_initialnode

- name: Check for Rancher Ingress cert
  kubernetes.core.k8s:
    name: tls-rancher-ingress
    kind: secret
    namespace: cattle-system
  register: tlsrancheringress
  when: vm_initialnode and not InitialSetup

- name: Create Rancher Ingress secret
  shell: kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=/etc/rancher/ssl/rancher-ingress.crt --key=/etc/rancher/ssl/rancher-ingress.key
  when: InitialSetup and vm_initialnode

- name: Check for CA Certificate secret
  kubernetes.core.k8s:
    name: tls-ca
    kind: secret
    namespace: cattle-system
  register: tlsca
  when: not InitialSetup and vm_initialnode

- name: Create CA Certificate secret
  shell: kubectl -n cattle-system create secret generic tls-ca --from-file=/etc/rancher/ssl/cacerts.pem
  when: InitialSetup and vm_initialnode

- name: Make sure ingress setup jobs complete
  shell: kubectl wait --for=condition=complete job/{{ item }} -n ingress-nginx --timeout=30s
  loop:
    - ingress-nginx-admission-create
    - ingress-nginx-admission-patch
  changed_when: false
  when: InitialSetup and vm_initialnode

- name: Wait for ingress-nginx pods to be ready
  shell: kubectl get pod -n ingress-nginx
  register: pods
  retries: 3
  delay: 30
  until: '"1/1" in pods.stdout'
  changed_when: false
  when: InitialSetup and vm_initialnode

- name: Wait for ingress-nginx controller to be ready
  shell: kubectl wait -n ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
  when: InitialSetup and vm_initialnode

- name: Allow initial kube setup to complete
  pause:
    seconds: 90
  when: InitialSetup

- name: Install Rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: cattle-system
    create_namespace: false
    values:
      ingress.tls.source: tls-rancher-ingress
      hostname: '{{ rancher_Hostname }}'
      privateCA: true
      bootstrapPassword: '{{ rancher_bootstrappassword }}'
      replicas: 3
      tls: external
  when: InitialSetup and vm_initialnode