---
- hosts: rancher
  gather_facts: yes
  become: yes
  roles:
    - role: common
    - role: kubernetes/common
    - role: kubernetes/rke
    - role: kubernetes/rancher
    - role: kubernetes/ranchermgmt

  post_tasks:
    - reboot:
      when: InitialSetup